project:
  type: website
  output-dir: docs

website:
  title: "DataDir"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bas-data-analy.qmd
        text: Basic Data Analytics
      - about.qmd

  sidebar:
    - id: bas-data-analy
      title: "Basic Data Analytics"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - "---"
        - section: Basic Data Analytics
          contents:
            - bas-data-analy.qmd
            - text: "descriptive stats"
              href: basic/desc-stats.qmd
        - "---"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



